services:
  paperless-ai:
    image: clusterzx/paperless-ai:2.7.6
    container_name: paperless-ai
    network_mode: bridge
    restart: unless-stopped
    depends_on:
      - papaerless-ngx
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - PAPERLESS_AI_PORT=${PAPERLESS_AI_PORT:-3000}
    ports:
      - "3000:${PAPERLESS_AI_PORT:-3000}"
    volumes:
      - paperless-ai_data:/app/data

  papaerless-ngx:
    image: paperlessngx/paperless-ngx:2.15
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - redis
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    env_file:
      - .env
    environment:
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_DBHOST=db
      - USERMAP_UID=${USERMAP_UID:-1000}
      - USERMAP_GID=${USERMAP_GID:-1000}
      - PAPERLESS_TIME_ZONE=${PAPERLESS_TIME_ZONE:-Etc/UTC}
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE:-eng}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - PAPERLESS_URL=${PAPERLESS_URL:-}
    volumes:
      - ${CONSUME_FOLDER:-./consume}:/usr/src/paperless/consume
      - ${MEDIA_FOLDER:-paperless-media}:/usr/src/paperless/media
      - ${DATA_FOLDER:-paperless-data}:/usr/src/paperless/data
    ports:
      - "${PAPERLESS_PORT:-8000}:8000"

  db:
    image: postgres:16
    container_name: paperless-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-paperless}
    volumes:
      - ${DATABASE_FOLDER:-paperless-db}:/var/lib/postgresql/data
    
  redis:
    image: redis:7
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
      - paperless-redis:/data

volumes:
  paperless-ai_data:
  paperless-media:
  paperless-data:
  paperless-db:
  paperless-redis: